filter:
  paths: [app/*]
tools:
  external_code_coverage: true
  php_analyzer: true
  php_mess_detector: true
  php_sim: true
  sensiolabs_security_checker: true
  php_changetracking: true
  php_cs_fixer:
      config: { level: psr2 }
checks:
  php:
    code_rating: true