language: php

php:
  - 5.6

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

branches:
  only:
    - master

before_script:
  - mysql -e 'create database <<database>>;'
  - cp .env.ci.php .env  #copy over CI environment configuration
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - chmod -R 777 storage/
  - php artisan migrate
  - php artisan db:seed
  - php -S localhost:8000 -t public &
  - sleep 5 # give artisan serve some time to start
  - php vendor/bin/codecept build
  - cp tests/acceptance.suite.yml.ci tests/acceptance.suite.yml #copy over CI acceptance test configuration

script:
  - php vendor/bin/codecept run --report --coverage-xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token=<<access token>> --format=php-clover tests/_output/coverage.xml
after_failure:
  - cat storage/logs/laravel.log
  - cat tests/_output/*
